
import React, {useEffect, useState, createContext, useContext} from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Routes, Route, Link, useNavigate } from 'react-router-dom'
import Keycloak from 'keycloak-js'
import axios from 'axios'
import './ui.css'
const kc = new Keycloak({ url: (window as any).CFG?.VITE_KEYCLOAK_URL || import.meta.env.VITE_KEYCLOAK_URL, realm: (window as any).CFG?.VITE_KEYCLOAK_REALM || import.meta.env.VITE_KEYCLOAK_REALM || 'athena', clientId: (window as any).CFG?.VITE_KEYCLOAK_CLIENT_ID || import.meta.env.VITE_KEYCLOAK_CLIENT_ID || 'web' })
const AuthCtx = createContext({ token: null as string|null, profile: null as any, logout: ()=>{} })
function useAuth(){ return useContext(AuthCtx) }
function Protected({children}: any){ const {token}=useAuth(); const nav=useNavigate(); useEffect(()=>{ if(!token) nav('/login') },[token]); return token? children:null }
function Login(){ const [loading,setLoading]=useState(false); const { token }=useAuth(); const nav=useNavigate(); useEffect(()=>{ if(token) nav('/') },[token]); const signIn=()=>{ setLoading(true); kc.init({ pkceMethod: 'S256', checkLoginIframe: false,  onLoad:'login-required', checkLoginIframe:false }).then(()=>{ setLoading(false); nav('/') }) }; return <div className="container"><div className="card"><h2>Entrar</h2><button className="btn" onClick={signIn} disabled={loading}>{loading? '...' : 'Login com Keycloak'}</button></div></div> }
function Home(){ const {profile, logout}=useAuth(); return <div className="container"><div className="row"><div className="card" style={{flex:1}}><h2>Bem-vindo(a) {profile?.username}</h2><p><Link className="btn" to="/contas">Contas</Link></p><p><Link className="btn" to="/pagamentos">Pagamentos</Link></p><p><Link className="btn" to="/kyc">KYC</Link></p><button className="btn" onClick={logout}>Sair</button></div></div></div> }
function Contas(){ const { token }=useAuth(); const [accId,setAccId]=useState('acc-web-001'); const [theme,setTheme]=useState('default'); const create=async()=>{ const sub = JSON.parse(atob(token!.split('.')[1])).sub; await fetch('http://accounts-service:8080/accounts',{ method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ id: accId, owner_id: sub, account_type:'flux', theme }) }).catch(()=>{}); alert('Conta requisitada'); }; const pdf=async()=>{ const res = await fetch(`http://localhost:9091/accounts/${accId}/statement.pdf`, { headers: { Authorization: `Bearer ${token}` } }); if(!res.ok){ alert('Falha'); return } const blob = await res.blob(); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `extrato-${accId}.pdf`; a.click(); }; return <div className="container"><div className="card"><h2>Contas</h2><input className="input" value={accId} onChange={e=>setAccId(e.target.value)} /><input className="input" value={theme} onChange={e=>setTheme(e.target.value)} /><button className="btn" onClick={create}>Criar conta</button> &nbsp; <button className="btn" onClick={pdf}>Extrato PDF</button></div></div> }
function Pagamentos(){ const [acc,setAcc]=useState('acc-web-001'); const [amount,setAmount]=useState('25.00'); const [txid,setTxid]=useState(''); const [qr,setQr]=useState(''); const [wireId,setWireId]=useState(''); const pix=async()=>{ const r = await axios.post('http://pix-service:8080/pix/charge',{ account_id:acc, amount:parseFloat(amount)}).catch(()=>null); if(r){ setTxid(r.data.txid); setQr(r.data.qr_code) } }; const simularWebhook=async()=>{ if(!txid) return alert('gere um charge'); await axios.post('http://pix-service:8080/pix/webhook',{ txid, amount: parseFloat(amount) }).catch(()=>{}); alert('PIX liquidado (simulado)') }; const ted=async()=>{ const r=await axios.post('http://wire-service:8080/ted/initiate',{ account_id:acc, bank:'001', branch:'0001', account:'12345-6', amount:parseFloat(amount) }).catch(()=>null); if(r) setWireId(r.data.id) }; const settle=async()=>{ if(!wireId) return; await axios.post(`http://wire-service:8080/wire/settle/${wireId}`).catch(()=>{}); alert('TED liquidado (simulado)') }; return <div className="container"><div className="card"><h2>Pagamentos</h2><input className="input" value={acc} onChange={e=>setAcc(e.target.value)} /><input className="input" value={amount} onChange={e=>setAmount(e.target.value)} /><div style={{height:8}}/><button className="btn" onClick={pix}>PIX (Criar)</button> &nbsp;<button className="btn" onClick={simularWebhook}>Simular webhook</button><p>txid: {txid}</p><p style={{wordBreak:'break-all'}}>QR: {qr}</p><div style={{height:8}}/><button className="btn" onClick={ted}>TED (Iniciar)</button> &nbsp;<button className="btn" onClick={settle}>Liquidar TED</button></div></div> }
function Kyc(){ const [customerId,setCustomerId]=useState('cust-001'); const [docFront,setDocFront]=useState('data:image/png;base64,...'); const [selfie,setSelfie]=useState('data:image/png;base64,...'); const send=async()=>{ const r = await fetch('http://kyc-service:8080/kyc/submit',{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ customer_id:customerId, doc_front:docFront, selfie }) }); const j = await r.json(); alert(JSON.stringify(j)) }; return <div className="container"><div className="card"><h2>KYC</h2><input className="input" value={customerId} onChange={e=>setCustomerId(e.target.value)} /><textarea className="input" rows={3} value={docFront} onChange={e=>setDocFront(e.target.value)}/><textarea className="input" rows={3} value={selfie} onChange={e=>setSelfie(e.target.value)}/><button className="btn" onClick={send}>Enviar</button></div></div> }
function Shell(){ const [token,setToken]=useState<string|null>(null); const [profile,setProfile]=useState<any>(null); useEffect(()=>{ kc.init({ pkceMethod: 'S256', checkLoginIframe: false,  onLoad:'check-sso', checkLoginIframe:false }).then(()=>{ if(kc.token){ setToken(kc.token); kc.loadUserProfile().then(setProfile) } }) },[]); const logout=()=>{ kc.logout(); setToken(null); setProfile(null) }; return <AuthCtx.Provider value={{token, profile, logout}}><BrowserRouter><Routes><Route path="/login" element={<Login/>} /><Route path="/" element={<Protected><Home/></Protected>} /><Route path="/contas" element={<Protected><Contas/></Protected>} /><Route path="/pagamentos" element={<Protected><Pagamentos/></Protected>} /><Route path="/kyc" element={<Protected><Kyc/></Protected>} /></Routes></BrowserRouter></AuthCtx.Provider> }
ReactDOM.createRoot(document.getElementById('root')!).render(<Shell/>)
