"""
Compliance Service Database Models
AML/KYC rules, alerts, sanctions, and limits
"""
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, DateTime, Boolean, Text, Numeric, Integer, Index
from sqlalchemy.dialects.postgresql import JSONB
from datetime import datetime
from decimal import Decimal
from app.db import Base, SCHEMA


class AMLRule(Base):
    """
    Anti-Money Laundering rules configuration
    """
    __tablename__ = "aml_rules"
    __table_args__ = (
        Index('ix_aml_rule_type_active', 'rule_type', 'is_active'),
        {"schema": SCHEMA}
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    name: Mapped[str] = mapped_column(String(128))
    description: Mapped[str] = mapped_column(Text)

    # Rule classification
    rule_type: Mapped[str] = mapped_column(String(32), index=True)
    # Types: VELOCITY, AMOUNT, PATTERN, GEOGRAPHY, PEP, SANCTIONS, BEHAVIOR

    # Rule conditions (JSON)
    conditions: Mapped[dict] = mapped_column(JSONB)
    # Example: {"max_daily_amount": 10000, "max_transactions_per_hour": 5}

    # Action when triggered
    action: Mapped[str] = mapped_column(String(32))  # BLOCK, ALERT, MANUAL_REVIEW, LOG
    severity: Mapped[str] = mapped_column(String(16))  # LOW, MEDIUM, HIGH, CRITICAL

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # Metadata
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by: Mapped[str] = mapped_column(String(128), nullable=True)


class AMLAlert(Base):
    """
    AML alerts generated by rule violations
    """
    __tablename__ = "aml_alerts"
    __table_args__ = (
        Index('ix_alert_customer_status', 'customer_id', 'status'),
        Index('ix_alert_severity_status', 'severity', 'status'),
        {"schema": SCHEMA}
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    rule_id: Mapped[str] = mapped_column(String(36), index=True)
    customer_id: Mapped[str] = mapped_column(String(128), index=True)
    transaction_id: Mapped[str] = mapped_column(String(128), nullable=True)

    # Alert classification
    alert_type: Mapped[str] = mapped_column(String(64), index=True)
    severity: Mapped[str] = mapped_column(String(16), index=True)

    # Status workflow
    status: Mapped[str] = mapped_column(String(32), index=True, default="OPEN")
    # Status: OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE, REPORTED

    # Alert details
    details: Mapped[dict] = mapped_column(JSONB, default=dict)
    risk_score: Mapped[int] = mapped_column(Integer, default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    resolved_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)
    resolved_by: Mapped[str] = mapped_column(String(128), nullable=True)
    resolution_notes: Mapped[str] = mapped_column(Text, nullable=True)

    # SAR (Suspicious Activity Report) tracking
    sar_filed: Mapped[bool] = mapped_column(Boolean, default=False)
    sar_reference: Mapped[str] = mapped_column(String(64), nullable=True)
    sar_filed_at: Mapped[datetime] = mapped_column(DateTime, nullable=True)


class SanctionsList(Base):
    """
    Sanctions and PEP lists for screening
    """
    __tablename__ = "sanctions_list"
    __table_args__ = (
        Index('ix_sanctions_name', 'name'),
        Index('ix_sanctions_document', 'document'),
        {"schema": SCHEMA}
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # List source
    list_type: Mapped[str] = mapped_column(String(32), index=True)
    # Types: OFAC, UN, EU, COAF_PEP, INTERPOL, INTERNAL

    # Person/Entity details
    name: Mapped[str] = mapped_column(String(256), index=True)
    name_normalized: Mapped[str] = mapped_column(String(256), index=True)  # For fuzzy matching
    document: Mapped[str] = mapped_column(String(32), nullable=True)
    country: Mapped[str] = mapped_column(String(3), nullable=True)  # ISO 3166-1 alpha-3
    aliases: Mapped[dict] = mapped_column(JSONB, default=list)

    # Additional info
    reason: Mapped[str] = mapped_column(Text, nullable=True)
    source_url: Mapped[str] = mapped_column(String(512), nullable=True)

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    added_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_updated: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class TransactionLimit(Base):
    """
    Transaction limits by customer type and KYC level
    """
    __tablename__ = "transaction_limits"
    __table_args__ = (
        Index('ix_limit_type_kyc', 'customer_type', 'kyc_level'),
        {"schema": SCHEMA}
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Customer classification
    customer_type: Mapped[str] = mapped_column(String(8), index=True)  # PF, PJ
    kyc_level: Mapped[int] = mapped_column(Integer, index=True)  # 0, 1, 2, 3

    # Transaction type
    transaction_type: Mapped[str] = mapped_column(String(32), index=True)
    # Types: PIX, TED, DOC, CARD, BOLETO, WITHDRAWAL, DEPOSIT, ALL

    # Limits (in BRL)
    daily_limit: Mapped[Decimal] = mapped_column(Numeric(18, 2))
    monthly_limit: Mapped[Decimal] = mapped_column(Numeric(18, 2))
    per_transaction_limit: Mapped[Decimal] = mapped_column(Numeric(18, 2))
    requires_approval_above: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=True)

    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class CustomerRiskProfile(Base):
    """
    Customer risk assessment and history
    """
    __tablename__ = "customer_risk_profiles"
    __table_args__ = {"schema": SCHEMA}

    customer_id: Mapped[str] = mapped_column(String(128), primary_key=True)

    # Risk assessment
    risk_level: Mapped[str] = mapped_column(String(16), default="LOW")  # LOW, MEDIUM, HIGH, CRITICAL
    risk_score: Mapped[int] = mapped_column(Integer, default=0)  # 0-100
    risk_factors: Mapped[dict] = mapped_column(JSONB, default=list)

    # PEP/Sanctions status
    is_pep: Mapped[bool] = mapped_column(Boolean, default=False)
    pep_details: Mapped[dict] = mapped_column(JSONB, nullable=True)
    sanctions_match: Mapped[bool] = mapped_column(Boolean, default=False)
    sanctions_details: Mapped[dict] = mapped_column(JSONB, nullable=True)

    # Monitoring flags
    enhanced_monitoring: Mapped[bool] = mapped_column(Boolean, default=False)
    is_blocked: Mapped[bool] = mapped_column(Boolean, default=False)
    block_reason: Mapped[str] = mapped_column(Text, nullable=True)

    # Timestamps
    last_assessment: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class TransactionCheck(Base):
    """
    Transaction compliance check history
    """
    __tablename__ = "transaction_checks"
    __table_args__ = (
        Index('ix_txcheck_customer_date', 'customer_id', 'checked_at'),
        {"schema": SCHEMA}
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    customer_id: Mapped[str] = mapped_column(String(128), index=True)
    transaction_id: Mapped[str] = mapped_column(String(128), nullable=True)

    # Check details
    transaction_type: Mapped[str] = mapped_column(String(32))
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 2))
    currency: Mapped[str] = mapped_column(String(3), default="BRL")

    # Decision
    decision: Mapped[str] = mapped_column(String(32))  # APPROVED, MANUAL_REVIEW, BLOCKED, ALERT
    risk_level: Mapped[str] = mapped_column(String(16))
    alerts_triggered: Mapped[dict] = mapped_column(JSONB, default=list)

    # Context
    source_service: Mapped[str] = mapped_column(String(64))
    checked_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    response_time_ms: Mapped[int] = mapped_column(Integer, nullable=True)
