FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json ./package.json
RUN npm i
COPY . .
RUN npm run build
FROM nginx:alpine
COPY dist/ /usr/share/nginx/html
COPY public/config.js /usr/share/nginx/html/config.js
EXPOSE 80
